[package]
name = "day7"
version = "0.1.0"
authors = ["Marcus Edvinsson <edvinsson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
slurp = "1.0.1"